

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:mysql://{AWS RDS Endpoint}/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: {RDS Mysql Admin id}
#    password: {rds Mysql Admin password}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 서버가 실행될때마다 db의 테이블 초기화 및 생성
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # 페이징 처리에 필요
    open-in-view: false # 어드벤스드로 나중에 설명
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

# 시큐리티
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

#server:
#  ssl:
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit

config:
  domain: "*"